Snap 1601 custom snap plugin dialog
senbox-org/snap-desktop pull request #194
Opened 2023-06-16 10:27 UTC by blucian

Added a custom dialog to display the rating for Community Plugins

This works in conjunction with the update of the deploy_nbm.py script from update_center.

2023-06-16 10:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/senbox-org/snap-desktop?pullRequest=194) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/senbox-org/snap-desktop?pullRequest=194) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/senbox-org/snap-desktop?pullRequest=194) it.</sub>

2023-06-16 11:01 UTC, kraftek requested changes
Replace System.err calls with logger calls

2023-06-16 11:58 UTC, kraftek approved these changes

2023-06-23 05:13 UTC, TomBlock approved these changes

2023-06-23 07:14 UTC, merged